### ISSUE TITLE
Get TODO.md up to date

### ISSUE THREAD

**Issue by canadajones** [canadajones/helpful-risk-emulator#3]
- [x] If and when combat details are set, put them in TODO.md:

- [x] Reorganize TODO.md

- [x] Expand upon TODO.md in areas where the language is unclear, or where one step should be multiple, and vice versa

- [x] Clean up extra stuff we don't need from TODO.md
